#include "stdafx.h"

#define CUSTOM_ENDLINE_DEF 

#define CONVERT_TO_METH_NAME(a,b) a##b
#undef WRAPPED_METH_DECL_
#define WRAPPED_METH_DECL_(a,b) a WRAPPED_METH_PREFIX(b) 

#undef WRAP_CALLTHRU_V0
#undef WRAP_CALLTHRU_V1
#undef WRAP_CALLTHRU_V2
#undef WRAP_CALLTHRU_V3
#undef WRAP_CALLTHRU_V4
#undef WRAP_CALLTHRU_V5
#undef WRAP_CALLTHRU_V6
#undef WRAP_CALLTHRU_V7
#undef WRAP_CALLTHRU_V8
#undef WRAP_CALLTHRU_V9
#undef WRAP_CALLTHRU_V10
#undef WRAP_CALLTHRU_V11
#undef WRAP_CALLTHRU_V12

#undef WRAP_CALLTHRU_V0_
#undef WRAP_CALLTHRU_V1_
#undef WRAP_CALLTHRU_V2_
#undef WRAP_CALLTHRU_V3_
#undef WRAP_CALLTHRU_V4_
#undef WRAP_CALLTHRU_V5_
#undef WRAP_CALLTHRU_V6_
#undef WRAP_CALLTHRU_V7_
#undef WRAP_CALLTHRU_V8_
#undef WRAP_CALLTHRU_V9_
#undef WRAP_CALLTHRU_V10_
#undef WRAP_CALLTHRU_V11_
#undef WRAP_CALLTHRU_V12_

//////////////////

#define WRAP_CALLTHRU_V0  { WRAP_CALLTHRU_PRE_IMPL(WRAP_METH_NAME, &_this); auto ret = WRAPPED_THIS_PREFIX -> WRAP_METH_NAME (); WRAP_CALLTHRU_POST_IMPL(WRAP_METH_NAME, &_this); return ret; }
#define WRAP_CALLTHRU_V1  { WRAP_CALLTHRU_PRE_IMPL(WRAP_METH_NAME, &_this); auto ret = WRAPPED_THIS_PREFIX -> WRAP_METH_NAME (v1); WRAP_CALLTHRU_POST_IMPL(WRAP_METH_NAME, &_this); return ret; }
#define WRAP_CALLTHRU_V2  { WRAP_CALLTHRU_PRE_IMPL(WRAP_METH_NAME, &_this); auto ret = WRAPPED_THIS_PREFIX -> WRAP_METH_NAME (v1,v2); WRAP_CALLTHRU_POST_IMPL(WRAP_METH_NAME, &_this); return ret; }
#define WRAP_CALLTHRU_V3  { WRAP_CALLTHRU_PRE_IMPL(WRAP_METH_NAME, &_this); auto ret = WRAPPED_THIS_PREFIX -> WRAP_METH_NAME (v1,v2,v3); WRAP_CALLTHRU_POST_IMPL(WRAP_METH_NAME, &_this); return ret; }
#define WRAP_CALLTHRU_V4  { WRAP_CALLTHRU_PRE_IMPL(WRAP_METH_NAME, &_this); auto ret = WRAPPED_THIS_PREFIX -> WRAP_METH_NAME (v1,v2,v3,v4); WRAP_CALLTHRU_POST_IMPL(WRAP_METH_NAME, &_this); return ret; }
#define WRAP_CALLTHRU_V5  { WRAP_CALLTHRU_PRE_IMPL(WRAP_METH_NAME, &_this); auto ret = WRAPPED_THIS_PREFIX -> WRAP_METH_NAME (v1,v2,v3,v4,v5); WRAP_CALLTHRU_POST_IMPL(WRAP_METH_NAME, &_this); return ret; }
#define WRAP_CALLTHRU_V6  { WRAP_CALLTHRU_PRE_IMPL(WRAP_METH_NAME, &_this); auto ret = WRAPPED_THIS_PREFIX -> WRAP_METH_NAME (v1,v2,v3,v4,v5,v6); WRAP_CALLTHRU_POST_IMPL(WRAP_METH_NAME, &_this); return ret; }
#define WRAP_CALLTHRU_V7  { WRAP_CALLTHRU_PRE_IMPL(WRAP_METH_NAME, &_this); auto ret = WRAPPED_THIS_PREFIX -> WRAP_METH_NAME (v1,v2,v3,v4,v5,v6,v7); WRAP_CALLTHRU_POST_IMPL(WRAP_METH_NAME, &_this); return ret; }
#define WRAP_CALLTHRU_V8  { WRAP_CALLTHRU_PRE_IMPL(WRAP_METH_NAME, &_this); auto ret = WRAPPED_THIS_PREFIX -> WRAP_METH_NAME (v1,v2,v3,v4,v5,v6,v7,v8); WRAP_CALLTHRU_POST_IMPL(WRAP_METH_NAME, &_this); return ret; }
#define WRAP_CALLTHRU_V9  { WRAP_CALLTHRU_PRE_IMPL(WRAP_METH_NAME, &_this); auto ret = WRAPPED_THIS_PREFIX -> WRAP_METH_NAME (v1,v2,v3,v4,v5,v6,v7,v8,v9); WRAP_CALLTHRU_POST_IMPL(WRAP_METH_NAME, &_this); return ret; }
#define WRAP_CALLTHRU_V10 { WRAP_CALLTHRU_PRE_IMPL(WRAP_METH_NAME, &_this); auto ret = WRAPPED_THIS_PREFIX -> WRAP_METH_NAME (v1,v2,v3,v4,v5,v6,v7,v8,v9,v10); WRAP_CALLTHRU_POST_IMPL(WRAP_METH_NAME, &_this); return ret; }
#define WRAP_CALLTHRU_V11 { WRAP_CALLTHRU_PRE_IMPL(WRAP_METH_NAME, &_this); auto ret = WRAPPED_THIS_PREFIX -> WRAP_METH_NAME (v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11); WRAP_CALLTHRU_POST_IMPL(WRAP_METH_NAME, &_this); return ret; }
#define WRAP_CALLTHRU_V12 { WRAP_CALLTHRU_PRE_IMPL(WRAP_METH_NAME, &_this); auto ret = WRAPPED_THIS_PREFIX -> WRAP_METH_NAME (v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12); WRAP_CALLTHRU_POST_IMPL(WRAP_METH_NAME, &_this); return ret; }

#define WRAP_CALLTHRU_V0_  { WRAP_CALLTHRU_PRE_IMPL(WRAP_METH_NAME, &_this); WRAPPED_THIS_PREFIX -> WRAP_METH_NAME (); WRAP_CALLTHRU_POST_IMPL(WRAP_METH_NAME, &_this); }
#define WRAP_CALLTHRU_V1_  { WRAP_CALLTHRU_PRE_IMPL(WRAP_METH_NAME, &_this); WRAPPED_THIS_PREFIX -> WRAP_METH_NAME (v1); WRAP_CALLTHRU_POST_IMPL(WRAP_METH_NAME, &_this); }
#define WRAP_CALLTHRU_V2_  { WRAP_CALLTHRU_PRE_IMPL(WRAP_METH_NAME, &_this); WRAPPED_THIS_PREFIX -> WRAP_METH_NAME (v1,v2); WRAP_CALLTHRU_POST_IMPL(WRAP_METH_NAME, &_this); }
#define WRAP_CALLTHRU_V3_  { WRAP_CALLTHRU_PRE_IMPL(WRAP_METH_NAME, &_this); WRAPPED_THIS_PREFIX -> WRAP_METH_NAME (v1,v2,v3); WRAP_CALLTHRU_POST_IMPL(WRAP_METH_NAME, &_this); }
#define WRAP_CALLTHRU_V4_  { WRAP_CALLTHRU_PRE_IMPL(WRAP_METH_NAME, &_this); WRAPPED_THIS_PREFIX -> WRAP_METH_NAME (v1,v2,v3,v4); WRAP_CALLTHRU_POST_IMPL(WRAP_METH_NAME, &_this); }
#define WRAP_CALLTHRU_V5_  { WRAP_CALLTHRU_PRE_IMPL(WRAP_METH_NAME, &_this); WRAPPED_THIS_PREFIX -> WRAP_METH_NAME (v1,v2,v3,v4,v5); WRAP_CALLTHRU_POST_IMPL(WRAP_METH_NAME, &_this); }
#define WRAP_CALLTHRU_V6_  { WRAP_CALLTHRU_PRE_IMPL(WRAP_METH_NAME, &_this); WRAPPED_THIS_PREFIX -> WRAP_METH_NAME (v1,v2,v3,v4,v5,v6); WRAP_CALLTHRU_POST_IMPL(WRAP_METH_NAME, &_this); }
#define WRAP_CALLTHRU_V7_  { WRAP_CALLTHRU_PRE_IMPL(WRAP_METH_NAME, &_this); WRAPPED_THIS_PREFIX -> WRAP_METH_NAME (v1,v2,v3,v4,v5,v6,v7); WRAP_CALLTHRU_POST_IMPL(WRAP_METH_NAME, &_this); }
#define WRAP_CALLTHRU_V8_  { WRAP_CALLTHRU_PRE_IMPL(WRAP_METH_NAME, &_this); WRAPPED_THIS_PREFIX -> WRAP_METH_NAME (v1,v2,v3,v4,v5,v6,v7,v8); WRAP_CALLTHRU_POST_IMPL(WRAP_METH_NAME, &_this); }
#define WRAP_CALLTHRU_V9_  { WRAP_CALLTHRU_PRE_IMPL(WRAP_METH_NAME, &_this); WRAPPED_THIS_PREFIX -> WRAP_METH_NAME (v1,v2,v3,v4,v5,v6,v7,v8,v9); WRAP_CALLTHRU_POST_IMPL(WRAP_METH_NAME, &_this); }
#define WRAP_CALLTHRU_V10_ { WRAP_CALLTHRU_PRE_IMPL(WRAP_METH_NAME, &_this); WRAPPED_THIS_PREFIX -> WRAP_METH_NAME (v1,v2,v3,v4,v5,v6,v7,v8,v9,v10); WRAP_CALLTHRU_POST_IMPL(WRAP_METH_NAME, &_this); }
#define WRAP_CALLTHRU_V11_ { WRAP_CALLTHRU_PRE_IMPL(WRAP_METH_NAME, &_this); WRAPPED_THIS_PREFIX -> WRAP_METH_NAME (v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11); WRAP_CALLTHRU_POST_IMPL(WRAP_METH_NAME, &_this); }
#define WRAP_CALLTHRU_V12_ { WRAP_CALLTHRU_PRE_IMPL(WRAP_METH_NAME, &_this); WRAPPED_THIS_PREFIX -> WRAP_METH_NAME (v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12); WRAP_CALLTHRU_POST_IMPL(WRAP_METH_NAME, &_this); }

#define WRAP_CALLTHRU_PRE_IMPL(a,b) 
#define WRAP_CALLTHRU_POST_IMPL(a,b)

#define WRAPPED_THIS_PREFIX _this->orig_dev
#define WRAPPED_METH_PREFIX(b) wrap_pass_dev_##b
#include "com_wrapper_dev_methods.inc"
#undef WRAPPED_METH_PREFIX
#undef WRAPPED_THIS_PREFIX

#define WRAPPED_THIS_PREFIX _this->orig_obj
#define WRAPPED_METH_PREFIX(b) wrap_pass_obj_##b
#include "com_wrapper_obj_methods.inc"
#undef WRAPPED_METH_PREFIX
#undef WRAPPED_THIS_PREFIX

#undef WRAP_CALLTHRU_PRE_IMPL 
#undef WRAP_CALLTHRU_POST_IMPL

#define WRAP_CALLTHRU_PRE_IMPL(a,b) wrap_InvokeEvent(CONVERT_TO_METH_NAME(METH_DEV_,a), 1, b)
#define WRAP_CALLTHRU_POST_IMPL(a,b) 
#define WRAPPED_THIS_PREFIX _this->orig_dev
#define WRAPPED_METH_PREFIX(b) wrap_pre_dev_##b
#include "com_wrapper_dev_methods.inc"
#undef WRAPPED_METH_PREFIX
#undef WRAPPED_THIS_PREFIX 
#undef WRAP_CALLTHRU_PRE_IMPL 
#undef WRAP_CALLTHRU_POST_IMPL

#define WRAP_CALLTHRU_PRE_IMPL(a,b) 
#define WRAP_CALLTHRU_POST_IMPL(a,b) wrap_InvokeEvent(CONVERT_TO_METH_NAME(METH_DEV_,a), 0, b) 
#define WRAPPED_THIS_PREFIX _this->orig_dev
#define WRAPPED_METH_PREFIX(b) wrap_post_dev_##b
#include "com_wrapper_dev_methods.inc"
#undef WRAPPED_METH_PREFIX
#undef WRAPPED_THIS_PREFIX 
#undef WRAP_CALLTHRU_PRE_IMPL 
#undef WRAP_CALLTHRU_POST_IMPL

#define WRAP_CALLTHRU_PRE_IMPL(a,b) wrap_InvokeEvent(CONVERT_TO_METH_NAME(METH_DEV_,a), 1, b) 
#define WRAP_CALLTHRU_POST_IMPL(a,b) wrap_InvokeEvent(CONVERT_TO_METH_NAME(METH_DEV_,a), 0, b) 
#define WRAPPED_THIS_PREFIX _this->orig_dev
#define WRAPPED_METH_PREFIX(b) wrap_prepost_dev_##b
#include "com_wrapper_dev_methods.inc"
#undef WRAPPED_METH_PREFIX
#undef WRAPPED_THIS_PREFIX 
#undef WRAP_CALLTHRU_PRE_IMPL 
#undef WRAP_CALLTHRU_POST_IMPL

#define WRAP_CALLTHRU_PRE_IMPL(a,b) wrap_InvokeEvent(CONVERT_TO_METH_NAME(METH_OBJ_,a), 1, b)
#define WRAP_CALLTHRU_POST_IMPL(a,b) 
#define WRAPPED_THIS_PREFIX _this->orig_obj
#define WRAPPED_METH_PREFIX(b) wrap_pre_obj_##b
#include "com_wrapper_obj_methods.inc"
#undef WRAPPED_METH_PREFIX
#undef WRAPPED_THIS_PREFIX 
#undef WRAP_CALLTHRU_PRE_IMPL 
#undef WRAP_CALLTHRU_POST_IMPL

#define WRAP_CALLTHRU_PRE_IMPL(a,b) 
#define WRAP_CALLTHRU_POST_IMPL(a,b) wrap_InvokeEvent(CONVERT_TO_METH_NAME(METH_OBJ_,a), 0, b) 
#define WRAPPED_THIS_PREFIX _this->orig_obj
#define WRAPPED_METH_PREFIX(b) wrap_post_obj_##b
#include "com_wrapper_obj_methods.inc"
#undef WRAPPED_METH_PREFIX
#undef WRAPPED_THIS_PREFIX 
#undef WRAP_CALLTHRU_PRE_IMPL 
#undef WRAP_CALLTHRU_POST_IMPL

#define WRAP_CALLTHRU_PRE_IMPL(a,b) wrap_InvokeEvent(CONVERT_TO_METH_NAME(METH_OBJ_,a), 1, b) 
#define WRAP_CALLTHRU_POST_IMPL(a,b) wrap_InvokeEvent(CONVERT_TO_METH_NAME(METH_OBJ_,a), 0, b) 
#define WRAPPED_THIS_PREFIX _this->orig_obj
#define WRAPPED_METH_PREFIX(b) wrap_prepost_obj_##b
#include "com_wrapper_obj_methods.inc"
#undef WRAPPED_METH_PREFIX
#undef WRAPPED_THIS_PREFIX 
#undef WRAP_CALLTHRU_PRE_IMPL 
#undef WRAP_CALLTHRU_POST_IMPL





